"""add resume analysis

Revision ID: 02b9fa5b37a4
Revises: e7aec2e28ee5
Create Date: 2026-08-16 15:45:38.495976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02b9fa5b37a4'
down_revision: Union[str, Sequence[str], None] = 'e7aec2e28ee5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('analysis', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'analysis')
    # ### end Alembic commands ###
