"""add extracted text to resumes

Revision ID: e7aec2e28ee5
Revises: cef674a5c41c
Create Date: 2026-08-09 22:48:27.824983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7aec2e28ee5'
down_revision: Union[str, Sequence[str], None] = 'cef674a5c41c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'resumes', 
         sa.Column('extracted_text', sa.Text(), nullable=True),
         )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'extracted_text')
    # ### end Alembic commands ###
